### ISSUE TITLE
Docker-compose hardcodes credentials that README claims are configurable

### ISSUE THREAD

**Issue by defreez** [RaiderSoft/AquiLLM#4]
## Issue Description
The README and .env.example indicate that database and storage credentials should be configured via environment variables, but docker-compose.yml hardcodes these values, overriding any user configuration.

### Database Password (line 368):
```
POSTGRES_PASSWORD=your_database_password
```

### Storage Credentials (lines 377-378):
```
STORAGE_ACCESS_KEY=your_minio_access_key
STORAGE_SECRET_KEY=your_minio_secret_key
```

## .env.example References
Line 9:
```
POSTGRES_PASSWORD=your_database_password
```

Lines 15-16:
```
STORAGE_ACCESS_KEY=your_minio_access_key
STORAGE_SECRET_KEY=your_minio_secret_key
```

## docker-compose.yml Hardcoded Values
Lines 3-6:
```yaml
environment:
  POSTGRES_PASSWORD: jacksonmadden
  STORAGE_ACCESS_KEY: dev
  STORAGE_SECRET_KEY: rickbailey
```

Lines 63-64 (MinIO service):
```yaml
environment:
  MINIO_ROOT_USER: dev
  MINIO_ROOT_PASSWORD: rickbailey
```

## Impact
- Users who follow the README instructions to set custom passwords in .env will be confused when the system uses hardcoded values instead
- Security concern: Anyone who reads the docker-compose.yml knows the database and storage passwords
- The hardcoded values override any .env configuration, making the documented configuration process ineffective
